apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neelastack
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neelastack-api
            port: {number: 8000}
